package diego.estrada.deersign

import android.graphics.Color
import android.graphics.drawable.Icon

var categoryList = mutableListOf(
    category(
        "ABC",
        R.drawable.abc,
        "#eea236"),
    category(
        "ANIMALES",
        R.drawable.animales,
        "#42a5f5"),
    category(
        "COLORES",
        R.drawable.colores,
        "#92d36e"),
    category(
        "COMIDA",
        R.drawable.comida,
        "#ff5d55"),
    category(
        "CUERPO",
        R.drawable.cuerpo,
        "#c238eb"),
    category(
        "DÍAS",
        R.drawable.dias,
        "#929292"),
    category(
        "FRUTAS",
        R.drawable.frutas,
        "#fefb64"),
    category(
        "HOGAR",
        R.drawable.hogar,
        "#d68227"),
    category(
        "LUGARES",
        R.drawable.lugares,
        "#eea236"),
    category(
        "MESES",
        R.drawable.meses,
        "#42a5f5"),
    category(
        "NÚMEROS",
        R.drawable.numeros,
        "#92d36e"),
    category(
        "PERSONAS",
        R.drawable.personas,
        "#ff5d55"),
    category(
        "PREGUNTAS",
        R.drawable.preguntas,
        "#c238eb"),
    category(
        "PREPOSICIONES",
        R.drawable.preposiciones,
        "#929292"),
    category(
        "PRONOMBRES",
        R.drawable.pronombres,
        "#fefb64"),
    category(
        "PUESTOS",
        R.drawable.comida,
        "#d68227"),
    category(
        "COLORES",
        R.drawable.colores,
        "#eea236"),
    category(
        "ABC",
        R.drawable.abc,
        "#42a5f5"),
    category(
        "DEPORTES",
        R.drawable.deportes,
        "#92d36e"),
    category(
        "COMIDA",
        R.drawable.comida,
        "#ff5d55"),
    category(
        "COLORES",
        R.drawable.colores,
        "#c238eb"),
    category(
        "ABC",
        R.drawable.abc,
        "#929292"),
    category(
        "DEPORTES",
        R.drawable.deportes,
        "#fefb64"),
    )