package diego.estrada.deersign


import android.graphics.Color
import android.graphics.drawable.Icon
import android.util.Log.d
import android.util.Log.e

var modulosLista = mutableListOf(
    category(
        "ABC",
        R.drawable.abc,
        "#eea236",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
    ),
    category(
        "ANIMALES",
        R.drawable.animales,
        "#42a5f5",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
        ),
    category(
        "COLORES",
        R.drawable.colores,
        "#92d36e",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
        ),
    category(
        "COMIDA",
        R.drawable.comida,
        "#ff5d55",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
        ),
    category(
        "CUERPO",
        R.drawable.cuerpo,
        "#c238eb",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
        ),
    category(
        "DÍAS",
        R.drawable.dias,
        "#929292",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
        ),
    category(
        "FRUTAS",
        R.drawable.frutas,
        "#3CA99B",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
        ),
    category(
        "HOGAR",
        R.drawable.hogar,
        "#d68227",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
        ),
    category(
        "LUGARES",
        R.drawable.lugares,
        "#eea236",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
        ),
    category(
        "MESES",
        R.drawable.meses,
        "#42a5f5",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
        ),
    category(
        "NÚMEROS",
        R.drawable.numeros,
        "#92d36e",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
        ),
    category(
        "PERSONAS",
        R.drawable.personas,
        "#ff5d55",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
        ),
    category(
        "PREGUNTAS",
        R.drawable.preguntas,
        "#c238eb",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
        ),
    category(
        "PREPOSICIONES",
        R.drawable.preposiciones,
        "#929292",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
        ),
    category(
        "PRONOMBRES",
        R.drawable.pronombres,
        "#3CA99B",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
        ),
    category(
        "OFICIOS",
        R.drawable.puestos,
        "#d68227",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
        ),
    category(
        "ROPA",
        R.drawable.ropa,
        "#eea236",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
    ),
    category(
        "SALUDOS",
        R.drawable.saludos,
        "#42a5f5",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
        ),
    category(
        "TIEMPO",
        R.drawable.tiempo,
        "#92d36e",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
        ),
    category(
        "TRANSPORTE",
        R.drawable.transporte,
        "#ff5d55",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
        ),
    category(
        "VERBOS",
        R.drawable.verbos,
        "#c238eb",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
        ),
    category(
        "VERBOS NARRATIVOS",
        R.drawable.verbos,
        "#929292",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
        ),
    category(
        "VERDURAS",
        R.drawable.verduras,
        "#3CA99B",
        mutableListOf(
            subCategorias(
                "ABC I",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC II",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
            subCategorias(
                "ABC III",
                "eea236",
                mutableListOf(
                    word(
                        "A",
                        R.raw.a
                    ),
                    word(
                        "B",
                        R.raw.b
                    ),
                    word(
                        "C",
                        R.raw.c
                    ),
                    word(
                        "D",
                        R.raw.d
                    ),
                    word(
                        "E",
                        R.raw.e
                    ),
                    word(
                        "F",
                        R.raw.f
                    ),
                    word(
                        "G",
                        R.raw.g
                    ),
                    word(
                        "H",
                        R.raw.h
                    ),
                )
            ),
        ),
        mutableListOf(
            word(
                "A",
                R.raw.a
            ),
            word(
                "B",
                R.raw.b
            ),
            word(
                "C",
                R.raw.c
            ),
            word(
                "D",
                R.raw.d
            ),
            word(
                "E",
                R.raw.e
            ),
            word(
                "F",
                R.raw.f
            ),
            word(
                "G",
                R.raw.g
            ),
            word(
                "H",
                R.raw.h
            ),
        )
)
)