package diego.estrada.deersign


import android.graphics.Color
import android.graphics.drawable.Icon

var modulosLista = mutableListOf(
    category(
        "ABC",
        R.drawable.abc,
        "#eea236",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
    ),
    category(
        "ANIMALES",
        R.drawable.animales,
        "#42a5f5",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
        ),
    category(
        "COLORES",
        R.drawable.colores,
        "#92d36e",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
        ),
    category(
        "COMIDA",
        R.drawable.comida,
        "#ff5d55",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
        ),
    category(
        "CUERPO",
        R.drawable.cuerpo,
        "#c238eb",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
        ),
    category(
        "DÍAS",
        R.drawable.dias,
        "#929292",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
        ),
    category(
        "FRUTAS",
        R.drawable.frutas,
        "#3CA99B",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
        ),
    category(
        "HOGAR",
        R.drawable.hogar,
        "#d68227",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
        ),
    category(
        "LUGARES",
        R.drawable.lugares,
        "#eea236",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
        ),
    category(
        "MESES",
        R.drawable.meses,
        "#42a5f5",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
        ),
    category(
        "NÚMEROS",
        R.drawable.numeros,
        "#92d36e",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
        ),
    category(
        "PERSONAS",
        R.drawable.personas,
        "#ff5d55",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
        ),
    category(
        "PREGUNTAS",
        R.drawable.preguntas,
        "#c238eb",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
        ),
    category(
        "PREPOSICIONES",
        R.drawable.preposiciones,
        "#929292",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
        ),
    category(
        "PRONOMBRES",
        R.drawable.pronombres,
        "#3CA99B",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
        ),
    category(
        "OFICIOS",
        R.drawable.puestos,
        "#d68227",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
        ),
    category(
        "ROPA",
        R.drawable.ropa,
        "#eea236",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
    ),
    category(
        "SALUDOS",
        R.drawable.saludos,
        "#42a5f5",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
        ),
    category(
        "TIEMPO",
        R.drawable.tiempo,
        "#92d36e",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
        ),
    category(
        "TRANSPORTE",
        R.drawable.transporte,
        "#ff5d55",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
        ),
    category(
        "VERBOS",
        R.drawable.verbos,
        "#c238eb",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
        ),
    category(
        "VERBOS NARRATIVOS",
        R.drawable.verbos,
        "#929292",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
        ),
    category(
        "VERDURAS",
        R.drawable.verduras,
        "#3CA99B",
        mutableListOf(
            subCategorias(
                "ABC I",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC II",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
            subCategorias(
                "ABC III",
                "#eea236",
                mutableListOf(
                    word(
                        "A",
                        "/A"
                    ),
                    word(
                        "B",
                        "/A"
                    ),
                    word(
                        "C",
                        "/A"
                    ),
                    word(
                        "D",
                        "/A"
                    ),
                    word(
                        "E",
                        "/A"
                    ),
                    word(
                        "F",
                        "/A"
                    ),
                    word(
                        "G",
                        "/A"
                    ),
                    word(
                        "H",
                        "/A"
                    ),
                    word(
                        "I",
                        "/A"
                    ),
                    word(
                        "J",
                        "/A"
                    )
                )
            ),
        )
        ),
)